### ISSUE TITLE
container.enchant.clue is missing localization

### ISSUE THREAD

**Issue by mystise** [ganymedes01/Et-Futurum#1]
Forge version 10.13.3.1395, only mod installed is Et Futurum version 1.0.1.

![2015-05-10_01 40 05](https://cloud.githubusercontent.com/assets/246232/7553428/9797a7d2-f6b5-11e4-99a1-d1c3340e5051.png)

**Comment by buttilda** [comment]
d'oh!
Fixed for the next version.
You can add these lines to the en_US.lang file if you'd like to fix the problem immediately:

# Containers

container.enchant.lapis.one=1 Lapis Lazuli
container.enchant.lapis.many=%d Lapis Lazuli
container.enchant.level.one=1 Enchantment Level
container.enchant.level.many=%d Enchantment Levels
container.enchant.clue=%s . . . ?
