### ISSUE TITLE
About mobs from the Future

### ISSUE THREAD

**Issue by labpaw** [ganymedes01/Et-Futurum#11]
Hi Gany! I've read that you can't add rabbits and guardians because "bouncy walk is only possible due to internal changes in minecraft." :smile:
I thought for a while and remembered mod called [Mo' Creatures](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272337-mo-creatures-v8-0-0-with-ghost-wyverns-minecraft-1). It's adds bunnies which are actually uses bouncy walk mechanic and as far as I know it's not a coremod (so it's doesn't modifies Minecraft through ASM).
So, maybe it's possible to add mobs from the future? :smile: It's only a question (and suggestion) so don't get me wrong :)

**Comment by buttilda** [comment]
Oh really? That's interesting. I'll look into it when I'm home to see how they've done it:3

**Comment by Tsyklop** [comment]
@ganymedes01 Mod alters the End?

**Comment by buttilda** [comment]
@Tsyklop What do you mean?

**Comment by Tsyklop** [comment]
@ganymedes01 Will the changes added to the End in version 1.9?

http://minecraft.gamepedia.com/15w31a

**Comment by buttilda** [comment]
They already have been added. Download the latest version of the mod to check it out

**Comment by Tsyklop** [comment]
@ganymedes01 Thx

**Comment by buttilda** [comment]
Rabbits have been added :3

**Comment by Xen1290** [comment]
You are awesome! @ganymedes01

**Comment by labpaw** [comment]
I knew that this is possible. Thanks @ganymedes01! What about other two mobs btw? Will you think about them later or they completely impossible to add?

**Comment by buttilda** [comment]
Guardians will be substantially more difficult to add due to the way they spawn.

Shulkers I'm not touching until MCP comes out for 1.9 (messing with obfuscated classes becomes way too complicated when it's something as complex as a mob)

But I do intent to add both of them at some point :3

**Comment by labpaw** [comment]
Glad to hear this. One day we will see them in the 1.7.10 :smile:
