### ISSUE TITLE
[Feature Request] A few random suggestions

### ISSUE THREAD

**Issue by mystise** [ganymedes01/Et-Futurum#13]
Activator Rails ejecting entities as per http://minecraft.gamepedia.com/Activator_rail

Difficulty per world (Can be locked)

Depth Strider enchantment

Anvil level requirements rebalance

Custom world types? (Probably really difficult)

Void fog removal?

Sorry if any of these have already been added.

**Comment by labpaw** [comment]
1) I support this if it possible.
2) Not worth it. And might be impossible to implement.
3) Would be cool.
4) Same.
5) Not worth it.
6) Void fog is 1.8 beta feature. 1.7.10 not affected.

**Comment by buttilda** [comment]
Moved to #19
