### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by labpaw** [ganymedes01/Et-Futurum#19]
-Features with a strikethrough can't/won't be ported
- [x] Carrots should restore 3 hunger points and Baked potatoes should restore 5 hunger points. (1.8)
- [x] ~~Written books changes ([Search here](http://minecraft.gamepedia.com/1.8) for Written books)~~
- [x] Baby animals changes ([Search here](http://minecraft.gamepedia.com/1.8) for Baby animals) (Not sure if possible)
- [x] ~~Arrows changes ([Search here](http://minecraft.gamepedia.com/1.8) for Arrows)~~
- [ ] Minecarts with TNT (Can be ignited with a flame enchanted bow - maybe?) (1.8)
- [x] Melons & ladders (Mined faster with an axe) (1.8)
- [ ] Buttons (Can be placed on the ceiling and on the ground) (1.8)
- [x] Packed ice (Mined faster with a pickaxe) (1.8)
- [x] ~~Hay bales changes. ([Search here](http://minecraft.gamepedia.com/1.8) for Hay bales)~~
- [x] ~~Furnace (When a furnace runs out of fuel, the smelting progress will rewind at 2× speed.)~~
- [x] New crafting recipes for Chiseled stone bricks, Cracked stone bricks, Moss stone, Mossy stone bricks
- [ ] Changes for Villages, Desert temples, Swampland. Not sure if possible, maybe it only possible to change dyed wool to stained clay in temples.
- [ ] Life Bar (Has a new animation for damage, that shows how many hearts the player just lost.)
- [x] Anvil repairing changes. Not sure if possible but maybe? Since enchanting changes possible, they might possible too.
- [x] Potion of Leaping (Can now be extended with redstone) (1.8.1)
- [ ] More statistics ([From 1.8.2](http://minecraft.gamepedia.com/1.8.2) (Low priority but maybe)
- [ ] Spectral arrow and Glowing status effect
- [ ] Activator Rails ejecting entities as per http://minecraft.gamepedia.com/Activator_rail
- [x] ~~Difficulty per world (Can be locked)~~
- [x] ~~Depth Strider enchantment~~
- [x] ~~Void fog removal~~
- [x] Colored beacon beams
- [ ] New command blocks
- [ ] Barrier Block
- [ ] Enchanted Golden Apple and Golden Apple changes (15w37a snapshot)
- [x] ~~Overpowered achievement~~
- [ ] Boats
- [ ] Elytra

Features of the Past:
- [x] Rose. Was removed in 1.7.2. Can we get it back? Just for fun.
- [x] ~~Horse saddle. It's even had a crafting recipe... but was removed. Not sure if it possible to add function to it. If no, just for fun maybe? :)~~
- [x] ~~Brick pyramid (http://minecraft.gamepedia.com/File:Infdev_Pyramid.png) maybe?~~
- [x] ~~Obsidian wall. Just like cobble walls. Mostly just for fun.~~
- [x] ~~Cog. Not sure if needed, just for fun.~~
- [x] Crying obsidian. Please bring this back :D Recipe: obsidian block and lapis lazuli.

**Comment by buttilda** [comment]
Were Obsidian Walls ever in the game?

**Comment by labpaw** [comment]
[Obsidian walls were used in Infdev to mark the positions of the cardinal directions.](http://minecraft.gamepedia.com/Removed_features)

**Comment by Xen1290** [comment]
Maybe also the Far Lands? Awesome thing for me :)

**Comment by buttilda** [comment]
Not worth it for the effort it would be to implement them. Not to mention you shouldn't go there, it's a buggy place =P

**Comment by labpaw** [comment]
Why not to add obsidian wall and crying obsidian? Only as decorative stuff. No other functions. Far Lands definitely not worth it :)

**Comment by Xen1290** [comment]
Exactly, Hahahah, however Far Lands was useless.
By the way +1 for crying obsidian and obsidian wall
And... The only thing that I hate in the new snapshot, is wait for use a tool when I switch the tool, please never implement it.

**Comment by buttilda** [comment]
Well the obsidian wall was just a line of obsidian blocks, it didn't have any different shape or texture.

Crying obsidian I might add as decoration, but it won't have the bed functionality.

**Comment by labpaw** [comment]
Of course it shouldn't have bed functionality. It's came from another reality :) Just a decorative block. About obsidian wall, can you just make this as cobble wall? Since it's from another reality, it's acts differently there :)

Edit: Also, would be cool if you can add somewhat mystic tooltips for old blocks. Something like: "It's came from another reality. It's lost its functionality during transfer."

**Comment by buttilda** [comment]
Then it wouldn't be a ported feature, it would be a new one, so it doesn't fit into Et Futurum.
And there's already a lot of mods out there that add walls of all sorts of materials (Extra Utilities and Carpenter Blocks are the first ones that come to mind)

**Comment by labpaw** [comment]
Ok, then. Just add crying obsidian :)

**Comment by buttilda** [comment]
Made this it "official" issue for feature requests :3

**Comment by labpaw** [comment]
Also, is The Killer Bunny planned?

**Comment by buttilda** [comment]
No.
It was pretty much removed from 1.8. It can only be accessed using commands.

**Comment by labpaw** [comment]
Oh, I thought it's have a spawn egg... it's not needed then.

**Comment by Xen1290** [comment]
Also Barrier block? (1.8)
http://minecraft.gamepedia.com/Barrier

**Comment by buttilda** [comment]
Added to the list :3

**Comment by quienti** [comment]
I love your mod :D Very good job :)
@ganymedes01 Have you planned to add gardian and Elder gardian ? :/

**Comment by labpaw** [comment]
Nice to see that you added anvil changes @ganymedes01 :) What about new crafting recipes? Why not to add them now? Or it's harder than I think?

**Comment by buttilda** [comment]
What new crafting recipes?

**Comment by buttilda** [comment]
>  Have you planned to add gardian and Elder gardian ? :/

@quienti yes, but they are quite hard to implement, so i don't know if they are even possible to do or how long it will take.

**Comment by labpaw** [comment]
@ganymedes01 "New crafting recipes for Chiseled stone bricks, Cracked stone bricks, Moss stone, Mossy stone bricks." (Check wikipage)

**Comment by buttilda** [comment]
Those have been added for a long time. They've been in the mod since 1.0.0

**Comment by labpaw** [comment]
Oh, I just blind.

**Comment by quienti** [comment]
Okey ! :)
So, good luck and courage !

**Comment by labpaw** [comment]
@ganymedes01 did you looked into other villagers changes? Maybe it's possible to implement some of them too.

**Comment by buttilda** [comment]
The trading and professions change can't be done without a core re-write.
Has anything else changed?

**Comment by labpaw** [comment]
Can you search [here](http://minecraft.gamepedia.com/1.8) for Villager trading and for Villagers (it's in Mobs category changes) sections and confirm that nothing can be done without ASM? Maybe it's possible to add new trades or remove some of them? Maybe XP for trading? Maybe breeding changes or crop harvesting? I just want to make sure that this isn't possible to do without ASM :)

Et Futurum definitely needs an ASM addon which hacks into everything :)

**Comment by buttilda** [comment]
The problem with trading is that it would break mods that add custom villagers.

And the XP on trading can only be done the same way the trading changes would, so the consequences would be the same.

**Comment by labpaw** [comment]
Ok, I knew that these changes too complex to implement.

**Comment by gabor7d2** [comment]
Can You add in the End Dungeons and Shulkers into the game ? Or are these already in the mod ?

EDIT: And also the bedrock sphere that teleports you to there.

**Comment by buttilda** [comment]
They aren't. But they are quite hard to implement without any code to reference.

**Comment by gabor7d2** [comment]
Oh, okay.

**Comment by border999** [comment]
Suggestion for a feature to add. Compatibility between the extra render settings added after 1.7.10, I.E. stuff like turning off entity shadows, and the latest 1.7.10 optifine version. So that players with optifine can access these features if they are ever added.

**Comment by labpaw** [comment]
@ganymedes01 
Enchanted Golden Apple regeneration level has been reduced from V to II.
Enchanted Golden Apple regeneration time has been reduced from 30 seconds to 20 seconds.
However, the Enchanted Golden Apple absorption level has been increased from I to IV to balance this.
Golden Apple regeneration level has been reduced from II to I.
15w37a snapshot

Also, what about Overpowered achievement which was added in 1.8?
Obtained by crafting an enchanted golden apple
Requires obtaining Getting an Upgrade first

**Comment by buttilda** [comment]
It looks like the changes to the golden apples aren't final. So I'd prefer to wait until they are before I implement it. But, I'm not sure if it's possible to do it without base edits )=

**Comment by chloeprince** [comment]
PLEASE PLEASE PLEASE Add the Barrier Block!  Oh, and the Invisible Bedrock Block too. No point in having an invisible block that everyone can just break. Sometimes you'll need it to be Unbreakable.

**Comment by buttilda** [comment]
It's on the list :)

**Comment by Tsyklop** [comment]
Please add the changes in The End from 1.9

**Comment by buttilda** [comment]
Just as a warning to whoever follows this:
I won't be porting the boats for now. There is still a huge list of issues regarding them on Mojang's issue tracker, so I don't think there's a point in replacing broken boats with a new broken boats.
Whenever they get around to fixing it I'll try to port it.

**Comment by dgcool20** [comment]
Could you add guardians or are they already in

**Comment by ziadbenaman** [comment]
[Feature Request] :  Falling onto a hay bale does only 20%  of the normal fall damage (1.9)   

your mod is great , thank you !

**Comment by buttilda** [comment]
Thank you:3 I'm not sure if that's possible without making a core mod, but I'll have a look when I can :)

**Comment by ghost** [comment]
Can you add the observer block to 1.7.10 please
