### ISSUE TITLE
Not forward compatible

### ISSUE THREAD

**Issue by purpleposeidon** [ganymedes01/Et-Futurum#2]
Looking in level.dat, I see that the domains used are "etfuturum:" rather than "minecraft:". Updating to MC1.8 (which presumably you'd no longer have Et Futurum installed at that point?) would of course cause blocks to get lost. FMLRemapEvent can be used to safely transition blocks to the minecraft domain; however there's the problem of mixed blocks, such as coarse dirt. FML has facilities now for replacing vanilla blocks; not sure what the name is.

Having replaced the vanilla blocks with 1.8-acting ones, there's then the matter of the block data that was named etfuturum:coarse_dirt. I suggest leaving a dummy block and using retrogen techniques to change out the dummy "etfuturum:coarse_dirt" blocks for "minecraft:dirt metadata=1" blocks. (Listen for ChunkDataEvent.Load; see if the chunk in its custom data has some key, and if it doesn't, add it and convert the data)

**Comment by buttilda** [comment]
I can use the remap event to register blocks with the "minecraft" id?
Do you have any material I can use as reference? Last time I tried using that event I couldn't get it to work properly.

**Comment by purpleposeidon** [comment]
The thing to do is to register the blocks as they should be named, and use FMLMissingMappingsEvent to keep save compatibility. Below is one of my uses for FMLMissingMappingsEvent. It... probably works?

```
@EventHandler
public void replaceDerpyNames(FMLMissingMappingsEvent event) {
    Object[][] corrections = new Object[][] {
            {"factorization:tile.null", Core.registry.factory_block},
            {"factorization:FZ factory", Core.registry.factory_block},
            {"factorization:tile.factorization.ResourceBlock", Core.registry.resource_block},
            {"factorization:FZ resource", Core.registry.resource_block},
            {"factorization:tile.lightair", Core.registry.lightair_block},
            {"factorization:FZ Lightair", Core.registry.lightair_block},
            {"factorization:tile.factorization:darkIronOre", Core.registry.dark_iron_ore},
            {"factorization:FZ dark iron ore", Core.registry.dark_iron_ore},
            {"factorization:tile.bedrock", Core.registry.fractured_bedrock_block},
            {"factorization:FZ fractured bedrock", Core.registry.fractured_bedrock_block},
            {"factorization:tile.factorization:darkIronOre", Core.registry.dark_iron_ore},
            {"factorization:FZ fractured bedrock", Core.registry.fractured_bedrock_block},
    };  
    HashMap<String, Block> corr = new HashMap<String, Block>();
    for (Object[] pair : corrections) {
        corr.put((String) pair[0], (Block) pair[1]);
    }   
    for (MissingMapping missed : event.get()) {
        Block value = corr.get(missed.name);
        if (value == null) {
            continue;
        }   
        if (missed.type == Type.BLOCK) {
            missed.remap(value);
        } else if (missed.type == Type.ITEM) {
            Item it = DataUtil.getItem(value);
            if (it != null) {
                missed.remap(it);
            }   
        }   
    }   
}   
```

**Comment by buttilda** [comment]
So, I looked into it, and it seems to me that the Remap event only fires when there's a missing mapping for an existing world. So I don't see how it would be possible to use it every single time

**Comment by purpleposeidon** [comment]
Ah, no. RemapEvent would be for backwards compatibility, not forwards. The
blocks should be straight up registered under minecraft, and the event is
so that you don't bust worlds that already have the mod installed.

**Comment by buttilda** [comment]
I can't register the blocks under the minecraft ID?
In the GameData class method addPrefix(String name), FML seems to automatically detect which mod is currently active and registers the block under its name... Am I missing something?

**Comment by purpleposeidon** [comment]
...oh. That's a problem.

**Comment by Shahelion** [comment]
I think another problem is you're trying to update a 1.7.10 world to 1.8, which usually doesn't go well, even with just vanilla sometimes.

**Comment by labpaw** [comment]
@ganymedes01 you might want to close this as it's probably impossible. You are already experienced this with Forestry's glass :smile:

**Comment by buttilda** [comment]
Indeed :3
