### ISSUE TITLE
Grass Path Issues / Improvements

### ISSUE THREAD

**Issue by msrEagle** [ganymedes01/Et-Futurum#21]
Ran into a couple of "issues" with the grass path block whilst testing:
- Grass can spread to dirt beneath a grass path block.
- The bounding box for the grass path is 1/16th too tall.
- The texture for the bottom face of the grass path block is the same as the top, where it should just be dirt.

**Comment by buttilda** [comment]
-That's a problem I'm not sure I can solve.
-Grass Paths do have a full bounding box.
-Easy fix!

**Comment by msrEagle** [comment]
You sure you can't solve the first one? Farmland doesn't do it, so that doesn't make sense.
Also, that sounds really dumb that paths actually have a full bounding box, looks quite odd too.

**Comment by buttilda** [comment]
Oh yeah, farmland does it, so indeed I should be able to :)

As for the bounding box... yeah I agree it looks dumb, but I'm just copying vanilla here

**Comment by msrEagle** [comment]
Yea, I guess. Not our fault that modded is better. :P

**Comment by buttilda** [comment]
Well to be fair, farmland also has a full bounding box.
