### ISSUE TITLE
Rename texture for Enchanting Table GUI

### ISSUE THREAD

**Issue by labpaw** [ganymedes01/Et-Futurum#22]
@ganymedes01 can you rename Enchanting Table GUI texture to enchanting_table_1.8.png or similar? Yes, this will break compatibility with some 1.8 resource packs but if 1.7 pack will replace vanilla texture with 1.8 GUI texture and Et Futurum will not be installed, the GUI will have unfunctional new slots.
Also, if the pack (For example Faithful32) contains just the same vanilla texture but with 32x32 resolution and Et Futurum is installed, you'll face with behavior [like this](http://i.imgur.com/WCJAZ3k.jpg). So, it's better to have separated from vanilla .png file for GUI.

**Comment by buttilda** [comment]
Yeah I'll do that.
Shouldn't you be using Faithful32 for 1.8 thought? :3

**Comment by labpaw** [comment]
Modded pack uses 1.7 texture. https://github.com/F32Organization/Faithful32-1.7.10 I always can use both but meh.

**Comment by Xen1290** [comment]
@Adaptivity when @ganymedes01  change the texture name, add the new gui with the new name in the faithful repository, is always a support for EtFutum users (like me)
EDIT: Oh you already done this, very good ! Nevermind
