### ISSUE TITLE
Wacky heart spam

### ISSUE THREAD

**Issue by Serifina** [ganymedes01/Et-Futurum#26]
Mobs with high health in mob grinders seem to produce hearts that simply scatter across huge areas. See [this reddit post](https://www.reddit.com/r/feedthebeast/comments/3jgvsp/graphical_bug_send_help/)

**Comment by buttilda** [comment]
that's hilarious lol
I'll see what I can do. For the time being just disable it in the config file

**Comment by buttilda** [comment]
Could you make sure you're running the latest Et-Futurum? I did some tweaks to that feature on the last version, maybe the problem fixed itself

**Comment by Serifina** [comment]
I am running the latest. I tend to stay extremely up-to-date (using the Curse Voice launcher for my own wacko custom pack) and I've observed this. I haven't been able to get screenshots of my own because they've seemed to be graphical glitches in my world, but it could be the design of my grinder. I have no idea if they interact with physical blocks or not.

**Comment by buttilda** [comment]
are you using the MFR grinders?

**Comment by Serifina** [comment]
Nope. In my case, it's a drop tower 3x3 inside using ExUtils Iron Spikes.

**Comment by buttilda** [comment]
Ah okay.
I think they mimic players. That's probably why this is happening. The hearts shouldn't be showing unless the damage is done by a player. I can probably work around this :3

**Comment by Shahelion** [comment]
Good to know what mod makes these hearts. I love them. One of iChun's mods allows you to decapitate mobs, and they die shortly after from massive damage, causing a large string of hearts to appear (it looks like about 20+).
