### ISSUE TITLE
Weapons causing over 4000 hearts of damage will crash the client.

### ISSUE THREAD

**Issue by Kucan** [ganymedes01/Et-Futurum#27]
When using weapons that cause over 4000 hearts of damage, such as TiC's Bane of Pig and similar instant death weapons, Et Futurum tries to spawn the correct amount of hearts and overloads with particles causing the client to crash.

[Here is a crash log.](http://pastebin.com/E9Yc3VHQ)

**Comment by buttilda** [comment]
Thanks for letting me know. I'll see what can be done.
