### ISSUE TITLE
Use Twilight Forest bunny model?

### ISSUE THREAD

**Issue by IdleMuse** [ganymedes01/Et-Futurum#28]
Hello. I really dislike the modern bunny model - Would it be possible to add a config option to use the Twilight Forest bunny model (if installed, obviously!) instead?

**Comment by labpaw** [comment]
It might be better to include TF bunny model in Et Futurum and add a config option for it. But @ganymedes01 probably will need permission from Benimatic to use it.

**Comment by buttilda** [comment]
I don't know if I like the idea at all.
If I add the option for the Twilight Forest bunny then soon enough someone will ask for me to support the Mo'Creatures bunny, and then some other bunny I haven't heard of, and so on.

Et Futurum ports features to 1.7, nothing else.

**Comment by IdleMuse** [comment]
Yeah, I guess that does make sense. It's a pity the vanilla bunny is so ugly in comparison.

Might just do this as a personal fork.

**Comment by buttilda** [comment]
You have my permission to do it :)
