### ISSUE TITLE
Crash on load?

### ISSUE THREAD

**Issue by InkDragon** [ganymedes01/Et-Futurum#3]
Crashlog: http://pastebin.com/tnPbDRMG

seems to be freaking out over prismarine textures despite me having them disabled in the config.

Config:
    B:"Armour Stand"=false
    B:Banners=true
    B:"Coarse Dirt"=true
    B:Doors=true
    B:"Enchanting Table"=false
    B:"Fancy Skulls"=true
    B:"Fences and Gates"=true
    B:"Fences, gates and dead bushes burn"=true
    B:"Inverted Daylight Sensor"=true
    B:"Iron Trapdoor"=true
    I:"Max number of 1.8 stones in a cluster"=33
    B:"Mushroom Blocks"=true
    B:Mutton=true
    B:"Old Gravel"=true
    B:Prismarine=false
    B:Rabbit=false
    B:"Recipes for prismarine"=false
    B:"Red Sandstone"=true
    B:"Skulls drop from charged creeper kills"=true
    B:"Slime Block"=true
    B:Sponge=true
    B:Stones=true

**Comment by buttilda** [comment]
Strange... doesn't happen with me. Maybe if you enable prismarine it will stop crashing? (fixed for the next release)

**Comment by InkDragon** [comment]
yup that currently fixes it

**Comment by buttilda** [comment]
Well leave it on until the fix is out so that you can at least play.
If any temples get generated, after you turn the config off they should disappear :3
