### ISSUE TITLE
[feature request][mod compatibility] TConstruct shovel does not make paths.

### ISSUE THREAD

**Issue by jena-s-lab** [ganymedes01/Et-Futurum#30]
Hello folks,

It's written in the title, the shovel from Tinker's Construct aren't able to create a path, so, if you are motivated and if it's depend of your side, that would be nice to fix that :) .

Thank you for this mod, it's awesome !

**Comment by buttilda** [comment]
I'll see if it can be done :)

**Comment by jena-th** [comment]
Thank you Gany ! :D
