### ISSUE TITLE
"Fancy Skulls" causes rendring glitches with display items.

### ISSUE THREAD

**Issue by EXTER7** [ganymedes01/Et-Futurum#31]
The "Fancy Skulls" seems to cause items in starage drawers, Thaumcraft pedestals, BiblioCraft shelves, and others to display with a solid square around them. This [Reddit thread](https://www.reddit.com/r/feedthebeast/comments/3k5clj/why_are_these_items_rendering_so_weirdly/) has more details and screenshots of this issue.

**Comment by buttilda** [comment]
Strange, I don't see any skulls being rendered in those screenshots. How could they be causing the problem is they aren't even there?

**Comment by buttilda** [comment]
Nvm, found the issue. Minecraft's GL state is so jumbled >__>
There were probably skulls in the background somewhere.

**Comment by Shahelion** [comment]
Oh so THAT'S what's causing this. I noticed the odd boxes behind some items. Although I don't have any pedestals yet, but it also happens with the scribing tools on a Research Table, and some items on the ground.
