### ISSUE TITLE
please make forge 1403 kompatible, build from source failed

### ISSUE THREAD

**Issue by ghost** [ganymedes01/Et-Futurum#33]
hello, the needed forge version are 1448, but i need it for forge 1403. i cannot build because gradle cannot load libs from libraries.minecraft.net (403 forbidden): http://pastebin.com/gJFKevLR
i must only change the minecraft version from "1.7.10-10.13.4.1448-1.7.10" to "1.7.10-10.13.3.1403-1.7.10" in build.gradle or? i hope the mod have no needed dependencies from the newer forge versions. i need a version for 1403 because this ist the last forge version in cauldron. the new kcauldron have a hidden player bug, that will not be fixed: https://gitlab.prok.pw/Prototik/KCauldron/issues/173 there are also many more bugs.
All mods like buildcraft, ic2, forrestry, thaumcraft run on older forge version. only et-futurum need forge 1448. please make a version for older forge versions. thanks.

**Comment by buttilda** [comment]
1448 is the latest recommended version of forge and it has been out for quite a few months now.
I will not support older versions.

Besides, why should I change my forge version because of Cauldron's bugs? Go tell them to fix their bug =P

**Comment by ghost** [comment]
I have tell them to fix this bug, but they have close the issue. Another people have also this bug. i hope spongepowered will be realase there mod this year xD
but can you please only compile your mod for forge 1403 (if this works) and send it to me: amifan@gmx.de ? i will tell my users that this version have no offiziell support. i will donate you some money whit paypal or bitcoin. many thanks.

**Comment by buttilda** [comment]
That's not how it works.
Go offer money to the cauldron people to fix their bugs. I can't make my mod compatible with old versions. It needs forge 1448, which is the stable version and that that you should be using.
