### ISSUE TITLE
Et Futurum breaks russian translation?

### ISSUE THREAD

**Issue by buttilda** [ganymedes01/Et-Futurum#34]
A user reported it on the forums that after installing Et Futurum his game switches to english despite it saying on the menu that it is in russian.

@Adaptivity would you know anything about this?

**Comment by labpaw** [comment]
o_O will investigate. Probably fault on his side.

**Comment by buttilda** [comment]
Yeah I think it's probably something derpy that he's doing or some other mod messing with translations. But he says he's sure it's Et Futurum causing it.

**Comment by labpaw** [comment]
Can't reproduce. Et Futurum just can't break localization since it's using vanilla assets system for its localization as almost every mod doing the same thing in 1.7.10

**Comment by buttilda** [comment]
Yeah, that's what I thought

**Comment by user707** [comment]
Hello there. 
I was the one who reported this issue on minecraftforum.
It is strange, but i have definitely language break, even only one this mod installed.

I'm tried to analyse the launch logs of the minecraft, and didn't find any useful information about the mod and the language.

The only one strange thing i noticed: the mod has the language folder in assets/minecraft/lang subfolder, but usually other mods have this subfolder in assets/modname/lang.
I didn't understand anything in mod programming, so it may means nothing.

But anyway, can you try to help me to resolve this problem? :)
I can upload the logs and screenshots.

**Comment by buttilda** [comment]
I'll move the lang folder to assets/etfuturum/lang but I doubt it will help. Feel free to speak russian if you prefer. @Adaptivity is russian (i think) =P

**Comment by labpaw** [comment]
@ganymedes01 you shouldn't move anything. it's 100% user mistake. Especially since this will not solve the problem.
@user707 Можешь залить мне полностью папку .minecraft куда-нибудь? Яндекс.диск, dropbox, куда угодно.

**Comment by labpaw** [comment]
Since you are already done this... can you drop a new build to @user707?

**Comment by buttilda** [comment]
Yeah, I'll make a build. If it doesn't work I'll revert the change.

**Comment by buttilda** [comment]
@user707 mind trying this?
https://www.dropbox.com/s/wccj529iv9h11ip/Et%20Futurum-1.4.3.jar?dl=0

**Comment by user707** [comment]
@Adaptivity нет проблем, уже заливается :)
@ganymedes01 yes, one minute plz

**Comment by user707** [comment]
@ganymedes01 Heh, its allright now! Now it is in Russian. Thanks very very much :D

**Comment by user707** [comment]
@Adaptivity я хз почему так, но все заработало. Вот ссылка, если еще актуально :) https://yadi.sk/d/KuDsrvp-jED6R

Спасибо большое вам обоим :)

**Comment by labpaw** [comment]
@user707 Да ладно, нет проблем :)
@ganymedes01 This was a really strange issue :) Never occurred for me. Glad it's fixed now.

**Comment by buttilda** [comment]
Strange that the folder was causing an issue to him but not to you.
What OS do you guys use?

**Comment by user707** [comment]
i have Windows 10 x64

**Comment by labpaw** [comment]
I'm on Windows 7 x64

**Comment by buttilda** [comment]
Weird...
well I have no idea why what I did fixed it, but it did. Glad the issue was fixed =P
