### ISSUE TITLE
Shovel right click overrides other shovel abilities

### ISSUE THREAD

**Issue by SarahGreyWolf** [ganymedes01/Et-Futurum#37]
With Et-Futurum installed, abilities like Botania's shovels ability to turn dirt into farmland are overridden by it making a grass path.

**Comment by buttilda** [comment]
Well, either disable the Grass Paths in the Et Futurum config file, or make sure to use the shovels only on dirt. No other way around it unfortunately.

I can't change the way it's done since it wasn't my idea. I just copied vanilla.

**Comment by Piratdu52** [comment]
Why not a simple blacklist id ?
