### ISSUE TITLE
Slime Blocks

### ISSUE THREAD

**Issue by icynewyear** [ganymedes01/Et-Futurum#40]
When you jump on a slime block you will occasionaly sink into it. When you do you will be locked to a 1x1 area and cannot leave even in creative. Upon reloading the world terrain does not generate.

**Comment by buttilda** [comment]
Are you using the latest version? I remember fixing that issue

**Comment by icynewyear** [comment]
Using version 1.4.3

**Comment by buttilda** [comment]
On my bad, the fix isn't in that version XD
I'll get an update out later today :3

**Comment by icynewyear** [comment]
Awesome. Thanks much :)
