### ISSUE TITLE
Non-vanilla behaviours of etfuturum armour stand

### ISSUE THREAD

**Issue by Entoarox** [ganymedes01/Et-Futurum#41]
A few differences I came across while trying to use the armour stand as you would the vanilla one in 1.8:
- The custom name is not visible when the armour stand has the `invisible` tag set to 1
- The armour stand is impossible to hit when it has the `invisible` tag set to 1

**Comment by buttilda** [comment]
I'll see what I can do about it :3

**Comment by buttilda** [comment]
Those behaviours are defined from inside minecraft code. There's nothing I can do about it without turning Et Futurum into a core mod )=
