### ISSUE TITLE
Heart damage display not working in SMP

### ISSUE THREAD

**Issue by mrammy** [ganymedes01/Et-Futurum#44]
On servers the black heart damage display no longer appears like it does in SMP. Is this intended or a bug?

**Comment by buttilda** [comment]
It should be working on servers. I'll see what's going on

**Comment by mrammy** [comment]
[crash-2015-10-21_00.46.08-server.txt](https://gist.github.com/mrammy/02d44659634811d29ab7) Seems like your missing an @Side.Only or something ;). Also doesn't appear to work client side only.

**Comment by buttilda** [comment]
Yeah probably am XD

Also, be careful with running code from this repo, I don't always commit working and fully tested code. Don't blame me if it breaks your worlds. I don't mind you doing it of course, but you've ben warned :)

**Comment by mrammy** [comment]
Oh I'm well aware of breaking things. Just wanted to try it out. Working on a fix already.

**Comment by buttilda** [comment]
Last commit fixed the crash at startup, but there's still a crash when it tries to spawn the particles.
Minecraft's particle system is so annoying to mess with >_>

**Comment by buttilda** [comment]
I think it's fixed now. Ran it on a private server and it worked with no crashes :3

**Comment by mrammy** [comment]
You should really use sendToAllAround instead of sendToDimension, and you also managed to beat me to my pull request... lol

**Comment by buttilda** [comment]
sendToAllAround would send it to players that aren't in the same dimension. Which is pointless since they wouldn't see the particles =P

**Comment by buttilda** [comment]
Also, yup just saw your PR XD
Would you mind trying my latest fix first? If that is still not working I'll revert and merge your PR.
But I'm pretty sure what I did works because I tested it myself this time ;D

**Comment by mrammy** [comment]
no it wouldn't it uses TargetPoint in a dimension with a specified range. I can make a modified PR with this but it seems like what you did works even if it sends the message to everyone in the same dimension.
https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/fml/src/main/java/cpw/mods/fml/common/network/simpleimpl/SimpleNetworkWrapper.java#L206
https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/fml/src/main/java/cpw/mods/fml/common/network/NetworkRegistry.java#L82

**Comment by buttilda** [comment]
Oh right! For some reason I read that as "sendToAll", sorry XD
Yeah I'll use your method, it makes way more sense :3
Thanks!
