### ISSUE TITLE
Crash with rabbits

### ISSUE THREAD

**Issue by xeronut** [ganymedes01/Et-Futurum#49]
Hello!  I get the following crash when EF rabbits are affected by the gravity from StarMiner's satellites: http://pastebin.com/vTWpNAUj

This crash only occurs with the rabbits - endermites, the zombie villagers, and every mob from various other mods I've thrown at the StarMiner gravity cores all do not crash the game and seem to properly respect bring upside down etc.  This crash occurs when a satellite spawns over an area that could be populated with a rabbit - sometimes the mob spawns on top of the structure.  Here is a link to the forum (Japanese) in case you are not familiar with the mod: http://forum.minecraftuser.jp/viewtopic.php?f=13&t=17975  -edit- I forgot to mention - I've tried spawning directly over the core, and again on blocks outside the gravity radius and pushing the rabbit onto the satellite.  I've tried throwing rabbits with iChun's Gravity Gun as well.  All crash as soon as the mob is affected by the altered gravity, even when you drop it on TOP of the core (where gravity should be normal).

I am ashamed to admit this, but this has been an issue since at least the 1.3.x branch - I noticed it in a Lite pack I was constructing, had meant to report it, and completely forgot until this morning.  :(

Thanks for your time!

**Comment by buttilda** [comment]
That mod seems to replace the class that controls how the rabbits walk (they don't use the vanilla one because they hope instead of walking)

So I think think there's anything I can do unfortunately.. I'd have to stop the rabbits from hopping in order for the crash to stop and I don't really want to do that. Maybe report it to the other mod's author, they might have an idea of what can be done.

**Comment by xeronut** [comment]
Okay, fair enough.  Thank you for your response!

**Comment by buttilda** [comment]
If you manage to contact the other mod's dev point them to this page. I'd be happy to discuss a solution :)

**Comment by buttilda** [comment]
Closing this for now since it's not my fault.
If there's further developments I'll re-open it. Feel free to post new comments.
