### ISSUE TITLE
(suggestion/request) please add the ability to swap armors when right clicking on stand instead of taking them off the stand

### ISSUE THREAD

**Issue by ghost** [ganymedes01/Et-Futurum#52]
just that

when you right click on the stand it should take your current armor and put it on the stand and take the stand armor and put it on you. 

right now i have to go trough 4 steps take all my armor off. take all the items off the stand. put the armor on. and put the items 1 by 1 on the stand.

**Comment by buttilda** [comment]
Same as I described on the other issue. Unless it's a vanilla mechanic I'd rather not do it. I want my armour stands to behave as much as possible as the 1.8 ones. Sorry )=
