### ISSUE TITLE
Armor stand crash

### ISSUE THREAD

**Issue by Tencao** [ganymedes01/Et-Futurum#53]
So earlier, one of my users had a crash issue involving armor on the armor stand. I dont know much in terms of re-producing, but here's the crashlog I gathered.

http://pastebin.com/uhYwg48T

**Comment by buttilda** [comment]
That's a weird one...
No idea what's going on there, nothing related to Et Futurum is mentioned in the crash D=

**Comment by Tencao** [comment]
If it helps you further, I'll give you what they did to get this error, and how they eventually fixed it. 

/// I placed the Et Futurum Armour Stand at -7047, +6009, lvl 61 (now at lvl 59). I placed it for decoration to place leather armor on it and when I right click on it the game closes and states fatal error.

I tried the following to remove it but nothing worked: axe, bare fist.

I also tried the red matter pick axe I had on me, and that removed blocks under the stand and the stand fell to level 59. If I try to right click to place a block I am ejected from the game with a fatal error.

I was able to get it removed after putting all armor in tablet. Although I was not able to place gem boots in tablet as long as the stand was out. Once I was able to remove it I placed the stand in the void chest and then I could place gem boots in tablet. ///

After re-reading it, it might actually also be a mod-conflict with project e. If so, I'll also report it to them as well.

**Comment by Tencao** [comment]
http://pastebin.com/DMKdY1LZ

This was directly from my server, maybe this makes things easier?

This happened when I simply right clicked the armor stand

**Comment by buttilda** [comment]
Oh that last log helps a lot! Thank you!

**Comment by ghost** [comment]
@ganymedes01 he posted it in the projecte issue tracker as well, and i was quite confused as well with the first crash XD.

**Comment by buttilda** [comment]
@Tencao Do you mind trying 1.5.0 and letting me know if the crash still happens?And if so, send me the new crash report please :)

**Comment by Tencao** [comment]
Confirmed, it seems fixed. Gonna close.
