### ISSUE TITLE
1.5.0 skin is incompatible with Optifine

### ISSUE THREAD

**Issue by EzerArch** [ganymedes01/Et-Futurum#54]
Et Futurum 1.4.x worked with Optifine with no problem at all. But the 1.5.0 release has issue with rendering player skin with Optifine. I'm using the 64x64 skin.

Et Futurum 1.5.0 only, no mods or resource packs
![2015-12-03_22 16 47](https://cloud.githubusercontent.com/assets/6743303/11578375/0a4077d8-9a0c-11e5-9e55-8a1acf704258.png)

Et Futurum 1.5.0 with Optifine 1.7.10 HD U C1, no other mods or resource packs
![2015-12-03_22 19 18](https://cloud.githubusercontent.com/assets/6743303/11578376/0a4145d2-9a0c-11e5-81a7-406f4ad756d2.png)

Thanks.

**Comment by buttilda** [comment]
Optifine probably doesn't like the fact that the skin is bigger.
Not much I can do, you can turn that feature off in the config file for Et Futurum so that your player renders properly again (or remove Optifine)

**Comment by EzerArch** [comment]
> you can turn that feature off in the config file for Et Futurum so that your player renders properly again (or remove Optifine)

I discovered that when I was posting this issue: #55. Thank you!

EDIT:

For those who want:

> Setting `B:"Skin overlays"=false` can avoid the crash.

**Comment by border999** [comment]
I may be blind but I don't see any option that states, 'Disable 1.9 skins'

**Comment by buttilda** [comment]
Release 1.5.2 might solve this issue, I recommend you give it a try :)

**Comment by EzerArch** [comment]
Tried and approved. :)

**Comment by buttilda** [comment]
:D
