### ISSUE TITLE
Skin disfigurement?

### ISSUE THREAD

**Issue by Divineaspect** [ganymedes01/Et-Futurum#57]
We're having skin disfigurement issues.
Is this caused by the change to the 1.8 skins?

**Comment by buttilda** [comment]
Optifine is knows to cause issues. Do you have it installed?

**Comment by Divineaspect** [comment]
Not at all

**Comment by Divineaspect** [comment]
Fastcraft?

**Comment by buttilda** [comment]
I don't think fastcraft would cause problems.
Try with the latest release: http://minecraft.curseforge.com/projects/et-futurum/files/2270081

Alternatively, if you don't use the 1.8 skin style, you might as well just turn that feature off :)

**Comment by Divineaspect** [comment]
I've actually had a 1.8 skin for a long time, and am really looking foreward to having the disguise mode of that outer layer. 1.5.2 seems to have fixed it, thank you.

**Comment by buttilda** [comment]
Awesome! That's great to hear, because I've run out of ideas on how to implement this XD
