### ISSUE TITLE
Compatibility between altered enchanting and Extrautilities Division Sigil ritual.

### ISSUE THREAD

**Issue by Divineaspect** [ganymedes01/Et-Futurum#60]
At the moment, the 1.8 enchanting from et Futurum is incompatible with the division sigil ritual. The division sigil isn't recognizing the table to provide the information, etc.

https://github.com/rwtema/extrautilities/issues/783

**Comment by buttilda** [comment]
I can't fix it because I need to replace the enchanting table with my own block in order to change its interface. Any support for it will have to come from ExU's side.

The other option is to just disable the 1.8 enchanting mechanic using the config file.

**Comment by Revemohl** [comment]
I just tested a few things in here, and it looks like there were no problems in version 1.4.4 of Et Futurum. Can't something be done about this, like for example a config option to get the old behavior?

**Comment by buttilda** [comment]
That config option already exists. Just disable the 1.8 enchanting mechanics
