### ISSUE TITLE
Compatibility with Extra Utilities

### ISSUE THREAD

**Issue by quienti** [ganymedes01/Et-Futurum#65]
Hi !

I think your enchanting table is not compatible with `Extra utilities`
Because, when I try to activate the division sigil, it's don't work :/

`http://ftbwiki.org/Division_Sigil`

**Comment by buttilda** [comment]
Already reported here: #60

**Comment by quienti** [comment]
Oops, sorry :/

**Comment by buttilda** [comment]
It's okay XD It was a closed issue, I don't blame you for not seeing it
