### ISSUE TITLE
Feature Request - Chisel duplicate blocks

### ISSUE THREAD

**Issue by Tencao** [ganymedes01/Et-Futurum#66]
Is there any chance that you can add a basic detection method in place to see if chisel is installed, and if so, don't add some of the 1.8 mods like granite to the world gen, since by default, it gets messy when two mods are doing the same block worldgen with the same texture etc.

You can always add a config override to either replace the chisel worldgen with your own, or enable your world gen with chisel enabled (Just thinking of ways for this to be a better drop and play mod rather than running through a bunch of config options to manually disable this stuff)

**Comment by buttilda** [comment]
Well, my blocks are registered in the ore dictionary, so if chisel registers theirs as well our blocks should play nicely together.
As for the world gen, you can just turn it off in the config file by setting the cluster size to 0. It will take you only a second :)
