### ISSUE TITLE
Very buggy Slime Block

### ISSUE THREAD

**Issue by Xen1290** [ganymedes01/Et-Futurum#7]
Hi @ganymedes01 , I've a strange bug with slime block, if you reproduce that behavior:
![2015-06-02_17 46 22](https://cloud.githubusercontent.com/assets/8685029/7940166/7a335162-094f-11e5-9aa4-058f1047df42.png)
And when you try to go in the slime block, I fall down, the game freezes and you can't do anything.

**Comment by buttilda** [comment]
Very strange...
I'll look into this when I'm back home in a few days :)

**Comment by BBoldt** [comment]
lol @ganymedes01 

This is one of the strangest hilarious bugs I have ever seen.

You put a slime block in your inventory, your arms disappear. Place it in the world and step on it and the world melts away.

https://github.com/BBoldt/Unabridged/issues/362

**Comment by ghost** [comment]
I found that bug @ganymedes01 . GIVE ME BACK MY ARMS DAMMIT

**Comment by ghost** [comment]
and legs

**Comment by RAnders00** [comment]
Relevant reddit post: http://redd.it/39r26e

**Comment by ghost** [comment]
I made that too. Must spread the word.

**Comment by buttilda** [comment]
I think this is proof that I posses magical powers beyond my control.
I have no idea what on earth is going on there XD

**Comment by ghost** [comment]
THE CREATION HAS TURNED AGAINST ITS CREATOR

**Comment by BBoldt** [comment]
That's what he gets for breaking the laws of time!

**Comment by ghost** [comment]
I broke the eternal laws of spacetime, and this is what I get.

**Comment by Xen1290** [comment]
@ganymedes01 for this issue, the MFR Pink slime block do almost the same thing that slime block does, if you want to take a look

**Comment by buttilda** [comment]
Oh thanks for the recommendation!
I had a look and based my code on their solution (quite strongly, but I don't see any other way of implementing it). So yeah, this should be fixed :D

**Comment by Xen1290** [comment]
Thanks @ganymedes01! As always you are awesome!

**Comment by buttilda** [comment]
:D
