### ISSUE TITLE
Cannot create lingering potions using dragon breath

### ISSUE THREAD

**Issue by Entoarox** [ganymedes01/Et-Futurum#71]
With the 1.5.4 version, I am currently unable to use dragon breath in the brewing of lingering potions.
(Note, this is not a case of it not showing in NEI, I put the item in the stand and it isnt brewing)

**Comment by buttilda** [comment]
Can you make sure you're using a splash potion?
If so, can you send me a screenshot with your mouse over the potion (so I can see the metadata value and the tooltip)

**Comment by Entoarox** [comment]
My mistake, didnt know you needed splash potions, I thought dragonbreath was about making it lingering in the same way that gunpowder makes it splash, so user error, closing now! XD

**Comment by buttilda** [comment]
What you thought isn't illogical. It's how I'd have implemented it. But since all I'm doing is porting, I had to follow the wiki: http://minecraft.gamepedia.com/Lingering_Potion

**Comment by Entoarox** [comment]
That is exactly the same reason I had that assumption, I would have implemented it that way to!
