### ISSUE TITLE
Chorus Plant forces transluncent blocks to render their hidden sides

### ISSUE THREAD

**Issue by EzerArch** [ganymedes01/Et-Futurum#76]
This is the same bug I reported to MrCrayFish long time ago, and he fixed it just afterwards: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1282349-mrcrayfishs-furniture-mod-v3-6-the-christmas?comment=613, and with another mod I don't recall.

Once I place a Chorus Plant block, the sides of all water blocks within the chunk limit start to render:
![2016-02-14_18 24 23](https://cloud.githubusercontent.com/assets/6743303/13036220/5ad11480-d348-11e5-8e36-40311006c8a8.png)
![2016-02-14_18 24 34](https://cloud.githubusercontent.com/assets/6743303/13036221/5ad1c1a0-d348-11e5-9344-5c0908f0ea15.png)

It happens with glass blocks too:
![2016-02-14_18 26 59](https://cloud.githubusercontent.com/assets/6743303/13036233/a4287aba-d348-11e5-830a-bc28f6501466.png)
![2016-02-14_18 27 09](https://cloud.githubusercontent.com/assets/6743303/13036232/a42768fa-d348-11e5-8a89-76911a6f3316.png)

EDIT:
And it happens regardless of whether I'm using Optfine or [my resource packs](http://ezerarch.blogspot.com/p/resource-pack.html).
![2016-02-14_19 04 55](https://cloud.githubusercontent.com/assets/6743303/13036414/ef451c38-d34d-11e5-9732-fad5ea51b704.png)

**Comment by VincentVan91** [comment]
It happens also for slime block.
