### ISSUE TITLE
Missing NEI depdendency in gradle.build

### ISSUE THREAD

**Issue by IceDragon200** [ganymedes01/Et-Futurum#79]
While trying to build from the cli (yes, because I hate dealing with IDEs), several errors reported that `codechicken.nei` is not a package, or missing I've edited the build.gradle and added NEI to solve this problem locally, but this may affect others who wish to contribute to this mod.:

Adding these to the corresponding files should help anyone who tries to compile the mod locally.
`build.gradle`

``` groovy
repositories {
    mavenLocal()
    mavenCentral()

    maven {
        name "ChickenBones"
        url "http://chickenbones.net/maven/"
    }
}

dependencies {
    compile "codechicken:CodeChickenLib:${minecraft_version}-${code_chicken_lib_version}:dev"
    compile "codechicken:CodeChickenCore:${minecraft_version}-${code_chicken_core_version}:dev"
    compile "codechicken:NotEnoughItems:${minecraft_version}-${nei_version}:dev"
}
```

`gradle.properties`

```
minecraft_version=1.7.10

code_chicken_lib_version=1.1.3.138
code_chicken_core_version=1.0.7.46
nei_version=1.0.5.111
```

If there was a reason it wasn't added, please share with me the reason and or write it in the README for others as well 3:

**Comment by buttilda** [comment]
I didn't add it because I just put all of the dependency jars in the `libs` folder
I don't like to mess with the gradle files because they break on their own enough, if I start adding to them chances are they'll break for good XD
