### ISSUE TITLE
[Feature request] Colored beacon beams

### ISSUE THREAD

**Issue by mystise** [ganymedes01/Et-Futurum#8]

**Comment by buttilda** [comment]
Completely forgot about that one!

**Comment by buttilda** [comment]
So this is more complicated than I thought it was going to be. Sorry for taking so long. I'll get around to it eventually XD

**Comment by buttilda** [comment]
Moved to #19

**Comment by Shahelion** [comment]
Just so you know, Chisel 2 adds colored beacons now.
